-- MySQL Script generated by MySQL Workbench
-- Thu Apr 11 18:51:44 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema pubg_dw
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pubg_dw
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pubg_dw` DEFAULT CHARACTER SET utf8 ;
USE `pubg_dw` ;

-- -----------------------------------------------------
-- Table `pubg_dw`.`MATCH_DATE_DIMENSION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pubg_dw`.`MATCH_DATE_DIMENSION` (
  `match_date_key` INT NOT NULL AUTO_INCREMENT,
  `match_date` DATE NOT NULL,
  `match_day` INT NOT NULL,
  `match_month` INT NOT NULL,
  `match_year` INT NOT NULL,
  `weekend` TINYINT NOT NULL,
  PRIMARY KEY (`match_date_key`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pubg_dw`.`MATCH_ID_DIMENSION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pubg_dw`.`MATCH_ID_DIMENSION` (
  `match_id_key` INT NOT NULL AUTO_INCREMENT,
  `match_id` TEXT NOT NULL,
  PRIMARY KEY (`match_id_key`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pubg_dw`.`MATCH_MODE_DIMENSION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pubg_dw`.`MATCH_MODE_DIMENSION` (
  `match_mode_key` INT NOT NULL AUTO_INCREMENT,
  `match_mode` TEXT NOT NULL,
  PRIMARY KEY (`match_mode_key`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pubg_dw`.`TIME_IN_GAME_DIMENSION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pubg_dw`.`TIME_IN_GAME_DIMENSION` (
  `time_in_game_key` INT NOT NULL AUTO_INCREMENT,
  `time_from_beginning` BIGINT NOT NULL,
  PRIMARY KEY (`time_in_game_key`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pubg_dw`.`KILLER_DIMENSION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pubg_dw`.`KILLER_DIMENSION` (
  `killer_key` INT NOT NULL AUTO_INCREMENT,
  `player_name` TEXT NOT NULL,
  `killer_placement` DOUBLE NOT NULL,
  `killer_pos_x` DOUBLE NOT NULL,
  `killer_pos_y` DOUBLE NOT NULL,
  `killer_match_kills` BIGINT NOT NULL,
  `killer_survive_time` DOUBLE NOT NULL,
  `killer_team_id` BIGINT NOT NULL,
  `killer_team_placment` BIGINT NOT NULL,
  `killer_dist_ride` DOUBLE NOT NULL,
  `killer_dist_walk` DOUBLE NOT NULL,
  `killer_match_dmg` BIGINT NOT NULL,
  `killer_match_assists` BIGINT NOT NULL,
  `killer_match_dbno` BIGINT NOT NULL,
  `party_size` BIGINT NOT NULL,
  PRIMARY KEY (`killer_key`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pubg_dw`.`VICTIM_DIMENSION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pubg_dw`.`VICTIM_DIMENSION` (
  `victim_key` INT NOT NULL AUTO_INCREMENT,
  `player_name` TEXT NOT NULL,
  `victim_placement` DOUBLE NOT NULL,
  `victim_pos_x` DOUBLE NOT NULL,
  `victim_pos_y` DOUBLE NOT NULL,
  `victim_match_kills` BIGINT NOT NULL,
  `victim_survive_time` DOUBLE NOT NULL,
  `victim_team_id` BIGINT NOT NULL,
  `victim_team_placement` BIGINT NOT NULL,
  `victim_dist_ride` DOUBLE NOT NULL,
  `victim_dist_walk` DOUBLE NOT NULL,
  `victim_match_dmg` BIGINT NOT NULL,
  `victim_match_assists` BIGINT NOT NULL,
  `victim_match_dbno` BIGINT NOT NULL,
  `party_size` BIGINT NOT NULL,
  `killed_by` TEXT NOT NULL,
  PRIMARY KEY (`victim_key`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pubg_dw`.`DEATH_FACT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pubg_dw`.`DEATH_FACT` (
  `kill_count` INT NOT NULL,
  `player_count` INT NOT NULL,
  `match_date_key` INT NOT NULL,
  `match_id_key` INT NOT NULL,
  `match_mode_key` INT NOT NULL,
  `time_in_game_key` INT NOT NULL,
  `killer_key` INT NOT NULL,
  `victim_key` INT NOT NULL,
  `game_size` BIGINT NOT NULL,
  PRIMARY KEY (`match_date_key`, `match_id_key`, `match_mode_key`, `time_in_game_key`, `killer_key`, `victim_key`),
  INDEX `fk_DEATH_FACT_MATCH_ID_DIMENSION1_idx` (`match_id_key` ASC) VISIBLE,
  INDEX `fk_DEATH_FACT_MATCH_MODE_DIMENSION1_idx` (`match_mode_key` ASC) VISIBLE,
  INDEX `fk_DEATH_FACT_TIME_IN_GAME_DIMENSION1_idx` (`time_in_game_key` ASC) VISIBLE,
  INDEX `fk_DEATH_FACT_KILLER_DIMENSION1_idx` (`killer_key` ASC) VISIBLE,
  INDEX `fk_DEATH_FACT_VICTIM_DIMENSION1_idx` (`victim_key` ASC) VISIBLE,
  CONSTRAINT `fk_DEATH_FACT_MATCH_DATE_DIMENSION`
    FOREIGN KEY (`match_date_key`)
    REFERENCES `pubg_dw`.`MATCH_DATE_DIMENSION` (`match_date_key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DEATH_FACT_MATCH_ID_DIMENSION1`
    FOREIGN KEY (`match_id_key`)
    REFERENCES `pubg_dw`.`MATCH_ID_DIMENSION` (`match_id_key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DEATH_FACT_MATCH_MODE_DIMENSION1`
    FOREIGN KEY (`match_mode_key`)
    REFERENCES `pubg_dw`.`MATCH_MODE_DIMENSION` (`match_mode_key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DEATH_FACT_TIME_IN_GAME_DIMENSION1`
    FOREIGN KEY (`time_in_game_key`)
    REFERENCES `pubg_dw`.`TIME_IN_GAME_DIMENSION` (`time_in_game_key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DEATH_FACT_KILLER_DIMENSION1`
    FOREIGN KEY (`killer_key`)
    REFERENCES `pubg_dw`.`KILLER_DIMENSION` (`killer_key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DEATH_FACT_VICTIM_DIMENSION1`
    FOREIGN KEY (`victim_key`)
    REFERENCES `pubg_dw`.`VICTIM_DIMENSION` (`victim_key`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
